export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PAGINATION_LIMIT_EXCEEDED: 'PAGINATION_LIMIT_EXCEEDED',
  INVALID_QUERY_FIELD: 'INVALID_QUERY_FIELD',
  RATE_LIMITED: 'RATE_LIMITED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  DEPENDENCY_TIMEOUT: 'DEPENDENCY_TIMEOUT',
  RESPONSE_TOO_LARGE: 'RESPONSE_TOO_LARGE',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
